name: pinguin

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: uptime
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      REDIS_ADDR: redis:6379
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: timescale/timescaledb:latest-pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uptime

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
