version: '3.8'

services:
  api:
    build:
      target: production
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - ENV=production
    restart: unless-stopped

  db:
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: uptime
    restart: unless-stopped

  redis:
    restart: unless-stopped
