version: '3.8'

services:
  api:
    build:
      target: development
    volumes:
      - ..:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - ENV=development

  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uptime
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d

  redis:
    ports:
      - "6379:6379"

volumes:
  go-mod-cache: