# Base configuration (shared between dev and prod)
version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=uptime
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: timescale/timescaledb:latest-pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: